from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from yin_resume_api.models.base_model import Model
from yin_resume_api import util


class Education(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name_id=None, school_name=None, school_link=None, school_pic=None, diploma=None, graduation_time=None, desc=None):  # noqa: E501
        """Education - a model defined in OpenAPI

        :param name_id: The name_id of this Education.  # noqa: E501
        :type name_id: str
        :param school_name: The school_name of this Education.  # noqa: E501
        :type school_name: str
        :param school_link: The school_link of this Education.  # noqa: E501
        :type school_link: str
        :param school_pic: The school_pic of this Education.  # noqa: E501
        :type school_pic: str
        :param diploma: The diploma of this Education.  # noqa: E501
        :type diploma: str
        :param graduation_time: The graduation_time of this Education.  # noqa: E501
        :type graduation_time: str
        :param desc: The desc of this Education.  # noqa: E501
        :type desc: str
        """
        self.openapi_types = {
            'name_id': str,
            'school_name': str,
            'school_link': str,
            'school_pic': str,
            'diploma': str,
            'graduation_time': str,
            'desc': str
        }

        self.attribute_map = {
            'name_id': 'name_id',
            'school_name': 'school_name',
            'school_link': 'school_link',
            'school_pic': 'school_pic',
            'diploma': 'diploma',
            'graduation_time': 'graduation_time',
            'desc': 'desc'
        }

        self._name_id = name_id
        self._school_name = school_name
        self._school_link = school_link
        self._school_pic = school_pic
        self._diploma = diploma
        self._graduation_time = graduation_time
        self._desc = desc

    @classmethod
    def from_dict(cls, dikt) -> 'Education':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The education of this Education.  # noqa: E501
        :rtype: Education
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name_id(self) -> str:
        """Gets the name_id of this Education.


        :return: The name_id of this Education.
        :rtype: str
        """
        return self._name_id

    @name_id.setter
    def name_id(self, name_id: str):
        """Sets the name_id of this Education.


        :param name_id: The name_id of this Education.
        :type name_id: str
        """

        self._name_id = name_id

    @property
    def school_name(self) -> str:
        """Gets the school_name of this Education.


        :return: The school_name of this Education.
        :rtype: str
        """
        return self._school_name

    @school_name.setter
    def school_name(self, school_name: str):
        """Sets the school_name of this Education.


        :param school_name: The school_name of this Education.
        :type school_name: str
        """

        self._school_name = school_name

    @property
    def school_link(self) -> str:
        """Gets the school_link of this Education.


        :return: The school_link of this Education.
        :rtype: str
        """
        return self._school_link

    @school_link.setter
    def school_link(self, school_link: str):
        """Sets the school_link of this Education.


        :param school_link: The school_link of this Education.
        :type school_link: str
        """

        self._school_link = school_link

    @property
    def school_pic(self) -> str:
        """Gets the school_pic of this Education.


        :return: The school_pic of this Education.
        :rtype: str
        """
        return self._school_pic

    @school_pic.setter
    def school_pic(self, school_pic: str):
        """Sets the school_pic of this Education.


        :param school_pic: The school_pic of this Education.
        :type school_pic: str
        """

        self._school_pic = school_pic

    @property
    def diploma(self) -> str:
        """Gets the diploma of this Education.


        :return: The diploma of this Education.
        :rtype: str
        """
        return self._diploma

    @diploma.setter
    def diploma(self, diploma: str):
        """Sets the diploma of this Education.


        :param diploma: The diploma of this Education.
        :type diploma: str
        """

        self._diploma = diploma

    @property
    def graduation_time(self) -> str:
        """Gets the graduation_time of this Education.


        :return: The graduation_time of this Education.
        :rtype: str
        """
        return self._graduation_time

    @graduation_time.setter
    def graduation_time(self, graduation_time: str):
        """Sets the graduation_time of this Education.


        :param graduation_time: The graduation_time of this Education.
        :type graduation_time: str
        """

        self._graduation_time = graduation_time

    @property
    def desc(self) -> str:
        """Gets the desc of this Education.


        :return: The desc of this Education.
        :rtype: str
        """
        return self._desc

    @desc.setter
    def desc(self, desc: str):
        """Sets the desc of this Education.


        :param desc: The desc of this Education.
        :type desc: str
        """

        self._desc = desc
