from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from yin_resume_api.models.base_model import Model
from yin_resume_api import util


class Repo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, title=None, language=None, description=None):  # noqa: E501
        """Repo - a model defined in OpenAPI

        :param title: The title of this Repo.  # noqa: E501
        :type title: str
        :param language: The language of this Repo.  # noqa: E501
        :type language: object
        :param description: The description of this Repo.  # noqa: E501
        :type description: str
        """
        self.openapi_types = {
            'title': str,
            'language': object,
            'description': str
        }

        self.attribute_map = {
            'title': 'title',
            'language': 'language',
            'description': 'description'
        }

        self._title = title
        self._language = language
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'Repo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The repo of this Repo.  # noqa: E501
        :rtype: Repo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this Repo.


        :return: The title of this Repo.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Repo.


        :param title: The title of this Repo.
        :type title: str
        """

        self._title = title

    @property
    def language(self) -> object:
        """Gets the language of this Repo.


        :return: The language of this Repo.
        :rtype: object
        """
        return self._language

    @language.setter
    def language(self, language: object):
        """Sets the language of this Repo.


        :param language: The language of this Repo.
        :type language: object
        """

        self._language = language

    @property
    def description(self) -> str:
        """Gets the description of this Repo.


        :return: The description of this Repo.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Repo.


        :param description: The description of this Repo.
        :type description: str
        """

        self._description = description
