from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from yin_resume_api.models.base_model import Model
from yin_resume_api import util


class SendMailRequestReceiver(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, mail=None, title=None, body=None):  # noqa: E501
        """SendMailRequestReceiver - a model defined in OpenAPI

        :param mail: The mail of this SendMailRequestReceiver.  # noqa: E501
        :type mail: str
        :param title: The title of this SendMailRequestReceiver.  # noqa: E501
        :type title: str
        :param body: The body of this SendMailRequestReceiver.  # noqa: E501
        :type body: str
        """
        self.openapi_types = {
            'mail': str,
            'title': str,
            'body': str
        }

        self.attribute_map = {
            'mail': 'mail',
            'title': 'title',
            'body': 'body'
        }

        self._mail = mail
        self._title = title
        self._body = body

    @classmethod
    def from_dict(cls, dikt) -> 'SendMailRequestReceiver':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The send_mail_request_receiver of this SendMailRequestReceiver.  # noqa: E501
        :rtype: SendMailRequestReceiver
        """
        return util.deserialize_model(dikt, cls)

    @property
    def mail(self) -> str:
        """Gets the mail of this SendMailRequestReceiver.


        :return: The mail of this SendMailRequestReceiver.
        :rtype: str
        """
        return self._mail

    @mail.setter
    def mail(self, mail: str):
        """Sets the mail of this SendMailRequestReceiver.


        :param mail: The mail of this SendMailRequestReceiver.
        :type mail: str
        """

        self._mail = mail

    @property
    def title(self) -> str:
        """Gets the title of this SendMailRequestReceiver.


        :return: The title of this SendMailRequestReceiver.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this SendMailRequestReceiver.


        :param title: The title of this SendMailRequestReceiver.
        :type title: str
        """

        self._title = title

    @property
    def body(self) -> str:
        """Gets the body of this SendMailRequestReceiver.


        :return: The body of this SendMailRequestReceiver.
        :rtype: str
        """
        return self._body

    @body.setter
    def body(self, body: str):
        """Sets the body of this SendMailRequestReceiver.


        :param body: The body of this SendMailRequestReceiver.
        :type body: str
        """

        self._body = body
